#!/usr/bin/env node
/**
 * Phase 1b — regenerate `apps/web/src/lib/generated/types.ts` from the
 * committed JSON schemas in `docs/schemas/`.
 *
 * Writes one `export interface <Title>` per schema file. Each schema property
 * becomes a single field with an inline TypeScript type derived from the
 * JSON-Schema `type` / `anyOf` shape. We deliberately inline the types rather
 * than emit per-column type aliases (what `json-schema-to-typescript` does)
 * because shared column names across tables — `date`, `symbol`, `run_id`,
 * `report_id` — would collide on each other at the module level.
 *
 * Usage:
 *   node apps/web/scripts/gen-types.mjs           # regenerate (idempotent)
 *   node apps/web/scripts/gen-types.mjs --check   # non-zero exit on diff
 *
 * Keeps the TS types the dashboard consumes in lockstep with the Python
 * Pydantic models — the Principle-2 typed SSOT contract crosses the
 * language boundary via `docs/schemas/*.schema.json`.
 */

import { readFile, readdir, writeFile, mkdir } from 'node:fs/promises';
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const webRoot = path.resolve(scriptDir, '..');
const repoRoot = path.resolve(webRoot, '../..');
const schemasDir = path.join(repoRoot, 'docs', 'schemas');
const outDir = path.join(webRoot, 'src', 'lib', 'generated');
const outFile = path.join(outDir, 'types.ts');

const HEADER = `/**
 * AUTO-GENERATED by apps/web/scripts/gen-types.mjs — DO NOT EDIT.
 *
 * Source of truth: docs/schemas/*.schema.json (emitted by
 * scripts/export_schemas.py from the Pydantic models in
 * src/snusmic_pipeline/backtest/schemas.py).
 *
 * Regenerate with \`npm --prefix apps/web run gen:types\`. CI verifies this
 * file matches the source schemas on every PR (see
 * .github/workflows/ci.yml).
 */
`;

function jsonTypeToTs(schemaType) {
  if (schemaType === 'string') return 'string';
  if (schemaType === 'number' || schemaType === 'integer') return 'number';
  if (schemaType === 'boolean') return 'boolean';
  if (schemaType === 'null') return 'null';
  if (schemaType === 'array') return 'unknown[]';
  if (schemaType === 'object') return 'Record<string, unknown>';
  return 'unknown';
}

function propertyToTsType(prop) {
  if (!prop || typeof prop !== 'object') return 'unknown';
  if (prop.const !== undefined) return JSON.stringify(prop.const);
  if (Array.isArray(prop.enum) && prop.enum.length > 0) {
    return prop.enum.map((v) => JSON.stringify(v)).join(' | ');
  }
  if (Array.isArray(prop.anyOf)) {
    const parts = prop.anyOf.map(propertyToTsType);
    const unique = Array.from(new Set(parts));
    return unique.join(' | ');
  }
  if (Array.isArray(prop.oneOf)) {
    return Array.from(new Set(prop.oneOf.map(propertyToTsType))).join(' | ');
  }
  if (Array.isArray(prop.type)) {
    return Array.from(new Set(prop.type.map(jsonTypeToTs))).join(' | ');
  }
  if (prop.type === 'array' && prop.items) {
    return `${propertyToTsType(prop.items)}[]`;
  }
  if (prop.type) return jsonTypeToTs(prop.type);
  return 'unknown';
}

function renderInterface(title, schema) {
  const properties = schema.properties || {};
  const required = new Set(Array.isArray(schema.required) ? schema.required : []);
  const descriptionLines = [];
  if (schema.description) {
    const desc = String(schema.description).trim().split('\n');
    descriptionLines.push('/**');
    for (const line of desc) descriptionLines.push(` * ${line}`);
    descriptionLines.push(' */');
  }

  const lines = [];
  lines.push(...descriptionLines);
  lines.push(`export interface ${title} {`);
  for (const [name, prop] of Object.entries(properties)) {
    const tsType = propertyToTsType(prop);
    // If the TS type already admits `null` (Pydantic field typed `T | None`),
    // the field is semantically "always present in the serialized row, maybe
    // null" — CSV/JSON rows emit the key with a null value. We therefore make
    // it required on the TS side to match existing call sites that treat these
    // as `T | null` rather than `T | null | undefined`.
    const nullable = /(^|\s|\|)null(\s|\||$)/.test(tsType);
    const optional = required.has(name) || nullable ? '' : '?';
    lines.push(`  ${JSON.stringify(name)}${optional}: ${tsType};`);
  }
  lines.push('}');
  return lines.join('\n');
}

function pascalCase(name) {
  return name
    .split(/[_\-\s]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

async function main() {
  const check = process.argv.includes('--check');
  const files = (await readdir(schemasDir)).filter(
    (name) => name.endsWith('.schema.json') && !name.endsWith('.v2.schema.json'),
  );
  if (files.length === 0) {
    throw new Error(`no committed schemas in ${schemasDir}`);
  }
  files.sort();

  const blocks = [HEADER];
  const titles = [];
  for (const file of files) {
    const schema = JSON.parse(await readFile(path.join(schemasDir, file), 'utf8'));
    const title = schema.title || pascalCase(file.replace('.schema.json', ''));
    titles.push(title);
    blocks.push(renderInterface(title, schema));
    blocks.push('');
  }

  // Back-compat aliases — let the dashboard import hand-written names while we
  // migrate call sites incrementally.
  blocks.push('// Hand-written name → generated name aliases (back-compat while call sites migrate).');
  blocks.push('export type Trade = ExecutionEvent;');
  blocks.push('');

  const next = blocks.join('\n');

  if (check) {
    if (!existsSync(outFile)) {
      console.error(`gen-types --check: ${outFile} missing`);
      process.exit(1);
    }
    const current = readFileSync(outFile, 'utf8');
    if (current !== next) {
      console.error(`gen-types --check: ${path.relative(repoRoot, outFile)} is stale.`);
      console.error('Regenerate with: npm --prefix apps/web run gen:types');
      process.exit(1);
    }
    console.log(`gen-types --check: ${files.length} schemas → ${path.relative(repoRoot, outFile)} up to date`);
    return;
  }

  await mkdir(outDir, { recursive: true });
  await writeFile(outFile, next, 'utf8');
  console.log(`wrote ${path.relative(repoRoot, outFile)} (${titles.length} interfaces: ${titles.join(', ')})`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
